# Generated by Django 5.2.1 on 2025-05-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='website',
        ),
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.city'),
        ),
    ]
