# Generated by Django 5.0.7 on 2025-05-14 14:44

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_city_remove_attraction_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['city', 'name'], 'verbose_name': 'جاذبه گردشگری', 'verbose_name_plural': 'جاذبه\u200cهای گردشگری'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AddField(
            model_name='attraction',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_type',
            field=models.CharField(choices=[('historical', 'تاریخی'), ('religious', 'مذهبی'), ('natural', 'طبیعی'), ('cultural', 'فرهنگی'), ('entertainment', 'تفریحی')], default='cultural', max_length=50, verbose_name='نوع جاذبه'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وبسایت'),
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='attractions.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام جاذبه'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام شهر'),
        ),
        migrations.AlterUniqueTogether(
            name='attraction',
            unique_together={('name', 'city')},
        ),
    ]
