# Generated by Django 5.0.7 on 2025-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_alter_attraction_created_at_alter_city_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='cit_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه شهر اکسل'),
        ),
    ]
