# Generated by Django 5.0.7 on 2025-05-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_attraction_cit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='cit_id',
        ),
        migrations.AddField(
            model_name='city',
            name='cit_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه شهر اکسل'),
        ),
    ]
